{
 "title": "4. Monitoring & Alerts",
 "tags": [ "project" ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Pod Restarts (1h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[1h]))"
    }
   ]
  },
  {
   "title": "Prometheus Targets Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "count(up == 1)" }
   ]
  },
  {
   "title": "Pod Restarts Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=~\"myapp|monitoring\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage (%) per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All Active Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  }
 ]
}