apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: telegram-alerts
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
    - name: telegram-alerts
      telegram_configs:
      - bot_token: "REDACTED_BOT_TOKEN"
        chat_id: 1150673339
        send_resolved: true
