apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - 'echo "<html><body><h1>HA Site</h1><p>Pod: ${POD_NAME}</p><p>Time: $(date)</p></body></html>"
          > /work-dir/index.html'
        command:
        - /bin/sh
        - -c
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: busybox
        imagePullPolicy: Always
        name: init-index
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: web-content
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: web-content
