apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: myapp-gitops:/Service:myapp/web-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"myapp-gitops:/Service:myapp/web-service"},"creationTimestamp":"2025-09-17T10:41:46Z","name":"web-service","namespace":"myapp","resourceVersion":"660033","uid":"e9ecbf83-edd2-43dc-a68b-689466d59cec"},"spec":{"clusterIP":"10.96.104.91","clusterIPs":["10.96.104.91"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"web"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-02-10T09:48:15Z"
  name: web-service
  namespace: myapp
  resourceVersion: "41583601"
  uid: c04209e0-5cca-42d3-87e0-40215646ccce
spec:
  clusterIP: 10.96.104.91
  clusterIPs:
  - 10.96.104.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
